name: Build, Test, & Deploy Go Libraries
on: [push, pull_request]
jobs:
  findchanges:
    runs-on: ubuntu-latest
    outputs:
      projs: ${{ steps.changes.outputs.projs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Find projects with changes in the pr
        id: changes
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} >> tmp.txt
          TOBUILD=$( cat projects.txt | xargs -I % -R 1 grep -o -m 1 ^% tmp.txt )
          echo ::set-output name=projs::${TOBUILD}
  buildchanges:
    runs-on: ubuntu-latest
    needs:
      - findchanges
    strategy:
      matrix:
        project: ${{ fromJSON(needs.findchanges.outputs.projs) }}
    steps:
      - name: Set up Go for ${{ matrix.project }}
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Check out monorepo
        uses: actions/checkout@v2
      - name: Run Go tests
        run: go test ./...
        working-directory: ./${{ matrix.project }}
      - name: Build Go lib
        run: go build -o ${{ matrix.project }}.so -buildmode=c-shared ${{ matrix.project }}.go
        working-directory: ./${{ matrix.project }}
