name: Test, Build & Deploy Changed Go Libs
on:
  push:
    - branches: 'main'
jobs:
  findchanges:
    runs-on: ubuntu-latest
    outputs:
      projs: ${{ steps.changes.outputs.projs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install apt-get packages
        run: sudo apt-get install -y jo
      - name: Find projects with changes in the pr
        id: changes
        run: |
          git diff --name-only ${{ github.event.before }} $GITHUB_SHA >> tmp.txt
          export TOBUILD=$( cat projects.txt | xargs -I {} -n 1 grep -o -m 1 ^{} tmp.txt | jo -a )
          echo "$TOBUILD"
          echo "::set-output name=projs::${TOBUILD}"
  buildchanges:
    runs-on: ubuntu-latest
    needs:
      - findchanges
    strategy:
      matrix:
        project: ${{ fromJSON(needs.findchanges.outputs.projs) }}
    steps:
      - name: Set up Go for ${{ matrix.project }}
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Check out monorepo
        uses: actions/checkout@v2
      - name: Run Go tests
        run: go test ./...
        working-directory: ./${{ matrix.project }}
      - name: Build Go lib
        run: go build -o ${{ matrix.project }}.so -buildmode=c-shared ${{ matrix.project }}.go
        working-directory: ./${{ matrix.project }}
      - name: Upload .so Artifact
        uses: actions/upload-artifact@v2
        with:
           name: ${{ matrix.project }}_$GITHUB_SHA
           path: ./${{ matrix.project }}/${{ matrix.project}}.so
