name: Push To Main CI (Test, Build, Deploy, Upload)
on:
  push:
    branches: 
      - 'main'
jobs:
  findchanges:
    runs-on: ubuntu-latest
    outputs:
      projs: ${{ steps.changes.outputs.projs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install apt-get packages
        run: sudo apt-get install -y jo
      - name: Find projects with changes in the pr
        id: changes
        run: |
          git fetch --depth=1 origin ${{ github.event.before }}
          git diff --name-only ${{ github.event.before }} $GITHUB_SHA >> tmp.txt
          export TOBUILD=$( cat projects.txt | xargs -I {} -n 1 grep -o -m 1 ^{} tmp.txt | jo -a )
          echo "$TOBUILD"
          echo "::set-output name=projs::${TOBUILD}"
  buildchanges:
    runs-on: ubuntu-latest
    needs:
      - findchanges
    strategy:
      matrix:
        project: ${{ fromJSON(needs.findchanges.outputs.projs) }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Set up Go for ${{ matrix.project }}
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Check out monorepo
        uses: actions/checkout@v2
      - name: Run Go tests
        run: go test ./...
        working-directory: ./${{ matrix.project }}
      - name: Build Go lib
        run: |  
          go build -o ${{ matrix.project }}.so -buildmode=c-shared ${{ matrix.project }}.go
          sudo mv ${{ matrix.project }}.so /usr/lib/${{ matrix.project }}.so
        working-directory: ./${{ matrix.project }}
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/980059950422/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: /usr/lib/${{ matrix.project }}.so
          destination: golibrepo/${{ github.event.head_commit.id }}
